### ISSUE TITLE
Is this multiplatform?

### ISSUE THREAD

**Issue by breznak** [fnkr/github-action-ghr#2]
Hello, 

is this "action" multiplatform, so it would run on all platforms supported by GH Actions? (Ubuntu, OSX, Windows)

- [x] and if so, could you please add `.zip` as a compression method (for Windows, but common everywhere)?

**Comment by fnkr** [comment]
Hi,

sorry for the late reply, for some reason I wasn't watching my own repository.

AFAIK GitHub Actions always run in Docker, and all GitHub-provided virtual environments support Docker and x86-64-based images. This means any workflow should be compatible with any action, including this one. Please let me know if you have any trouble integrating this action in your workflow.

Regarding support for zip archives: I will take a look at it, shouldn't be too hard to add this feature.

**Comment by fnkr** [comment]
@breznak zip support is now available. Does this work for you?

**Comment by breznak** [comment]
Thanks a lot for adding the .zip support! meanwhile I've started using a combination of `upload-artifacts` and GH releases, but I'll now retest with this action. Thank you
