### ISSUE TITLE
Failed to add secret. Name is invalid.

### ISSUE THREAD

**Issue by oxr463** [fnkr/github-action-ghr#5]
Cannot name secret `GITHUB_TOKEN`, or else it gives me the following warning,

>  Failed to add secret. Name is invalid.

**Comment by oxr463** [comment]
I fixed it by renaming the secret as follows:

`GITHUB_TOKEN: ${{ secrets.GHR_TOKEN }}`

**Comment by fnkr** [comment]
Duplicate of #6.
