### ISSUE TITLE
Personal Access Token Scopes

### ISSUE THREAD

**Issue by oxr463** [fnkr/github-action-ghr#6]
Not sure which permissions are required for creating a personal access token for this.

See: https://developer.github.com/apps/building-oauth-apps/scopes-for-oauth-apps

**Comment by oxr463** [comment]
> For a private repository you need repo scope and for a public repository you need public_repo scope.
Source: https://github.com/tcnksm/ghr#github-api-token

**Comment by fnkr** [comment]
You don't need to do this. The `GITHUB_TOKEN` secret is automatically created by GitHub (provides limited access to the current repository.

**Comment by fnkr** [comment]
You don't need to do this. The `GITHUB_TOKEN` secret is automatically provided by GitHub, which is also the reason why you can't add a secret with that name.

> GitHub automatically creates a GITHUB_TOKEN secret to use in your workflow. You can use the GITHUB_TOKEN to authenticate in a workflow run. [...] The token's permissions are limited to the repository that contains your workflow.

https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token
